#https://github.com/spring-cloud/spring-cloud-netflix/issues/3875

server:
  port: 9090
  
  
management:
  endpoints:
    web:
      exposure:
        include: '*'
        
        
hystrix:
  dashboard:
    proxy-stream-allow-list: '*'